import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import Provider from './Provider'
import './globals.css'

const uncutSans = localFont({
  src: [
    {
      path: '../public/fonts/Webfonts/UncutSans-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-LightItalic.woff2',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-Book.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-BookItalic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-Regular.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-RegularItalic.woff2',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-Medium.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-MediumItalic.woff2',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-Semibold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-SemiboldItalic.woff2',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-Bold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/fonts/Webfonts/UncutSans-BoldItalic.woff2',
      weight: '800',
      style: 'italic',
    },
  ],
  variable: '--font-uncut-sans',
  display: 'swap',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${uncutSans.variable} ${inter.variable} font-sans antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
